{{- $name := .Values.oidcIdentityProvider | required ".Values.oidcIdentityProvider is required." -}}

apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: {{ .Values.oidcIdentityProvider }} 
    mappingMethod: claim 
    type: OpenID
    openID:
      clientID: {{ .Values.bridgeEnvironmentVariables.BRIDGE_USER_AUTH_OIDC_CLIENT_ID }}
      clientSecret: 
        name: {{ .Values.secret.secretName }}
      claims: 
        {{- toYaml .Values.claims | nindent 8 }}
      issuer: {{ .Values.bridgeEnvironmentVariables.BRIDGE_USER_AUTH_OIDC_ISSUER_URL }}